import type { ThemeMeta } from "@/lib/theme"
import type { HotkeyAction, HotkeyConfig } from "@/config"

export type ClosedTasksTimeFilter =
  | "past_hour"
  | "past_4_hours"
  | "past_day"
  | "past_week"
  | "all_time"

export type RalphStatus =
  | "stopped"
  | "starting"
  | "running"
  | "pausing"
  | "paused"
  | "stopping"
  | "stopping_after_current"

export type Theme = "system" | "light" | "dark"

// =============================================================================
// ChatEvent – base interface + discriminated event shapes
// =============================================================================

/**
 * Base chat event interface.
 *
 * All events flowing through the Ralph UI conform to this shape.
 * The `type` field discriminates the event kind; the index signature
 * allows arbitrary extra properties (e.g. `subtype`, `sessionId`).
 *
 * **Prefer the narrower typed interfaces below** (e.g. `AssistantChatEvent`,
 * `UserMessageChatEvent`) whenever possible. Use type-guard functions
 * (`isAssistantMessage`, `isErrorEvent`, etc.) to narrow a `ChatEvent`
 * to the concrete shape.
 */
export interface ChatEvent {
  type: string
  timestamp: number
  /** Unique identifier for deduplication. Generated by server if not present. */
  id?: string
  [key: string]: unknown
}

// ---------------------------------------------------------------------------
// Discriminated event shapes
//
// Each interface below narrows the `type` field to a string literal (or
// literal union) and declares the properties specific to that event kind.
// These are used as the return types of type-guard functions (e.g.
// `event is UserMessageChatEvent`) so that downstream code can access
// typed properties without `as any`.
// ---------------------------------------------------------------------------

/** A user message sent as plain text. */
export interface UserMessageChatEvent extends ChatEvent {
  type: "user_message"
  message: string
}

/** A user turn, which may include tool results. */
export interface UserChatEvent extends ChatEvent {
  type: "user"
  message?: {
    role: string
    content: Array<{
      type: string
      tool_use_id?: string
      content?: string
      is_error?: boolean
      [key: string]: unknown
    }>
  }
  tool_use_result?: unknown
}

/** An assistant response with structured content blocks. */
export interface AssistantChatEvent extends ChatEvent {
  type: "assistant"
  message?: {
    id?: string
    content: AssistantContentBlock[]
    [key: string]: unknown
  }
}

/** A raw streaming event from the Claude SDK. */
export interface StreamChatEvent extends ChatEvent {
  type: "stream_event"
  event?: StreamEventPayload
}

/** Payload of a streaming event from the Claude SDK. */
export interface StreamEventPayload {
  type?: string
  message?: { id?: string; [key: string]: unknown }
  content_block?: {
    type?: string
    text?: string
    thinking?: string
    id?: string
    name?: string
    [key: string]: unknown
  }
  delta?: {
    type?: string
    text?: string
    thinking?: string
    partial_json?: string
    [key: string]: unknown
  }
  [key: string]: unknown
}

/** A result event with token usage information. */
export interface ResultChatEvent extends ChatEvent {
  type: "result"
  usage?: {
    inputTokens?: number
    outputTokens?: number
    totalTokens?: number
    input_tokens?: number
    output_tokens?: number
  }
}

/** An error event. */
export interface ErrorChatEvent extends ChatEvent {
  type: "error" | "server_error"
  error: string
}

/** A tool use event with execution metadata. */
export interface ToolUseChatEvent extends ChatEvent {
  type: "tool_use"
  tool: ToolName
  input?: Record<string, unknown>
  output?: string
  status?: "pending" | "running" | "success" | "error"
  duration?: number
  error?: string
}

/** Emitted when Ralph starts working on a task. */
export interface RalphTaskStartedChatEvent extends ChatEvent {
  type: "ralph_task_started"
  taskId?: string
}

/** Emitted when Ralph finishes working on a task. */
export interface RalphTaskCompletedChatEvent extends ChatEvent {
  type: "ralph_task_completed"
  taskId?: string
}

/** Emitted at the start of a Ralph session. */
export interface RalphSessionStartChatEvent extends ChatEvent {
  type: "ralph_session_start"
  sessionId?: string
}

/** A system event (e.g., init). */
export interface SystemChatEvent extends ChatEvent {
  type: "system"
  subtype?: string
}

/** An assistant text event (plain text content). */
export interface AssistantTextChatEvent extends ChatEvent {
  type: "assistant_text" | "text"
  content: string
}

/** A task lifecycle event. */
export interface TaskLifecycleChatEvent extends ChatEvent {
  type: "task_lifecycle"
  action: "starting" | "completed"
  taskId: string
}

export type TaskStatus = "open" | "in_progress" | "blocked" | "deferred" | "closed"

export interface TaskDependency {
  id: string
  status: TaskStatus
  dependency_type: string
}

export interface Task {
  id: string
  title: string
  description?: string
  status: TaskStatus
  priority?: number
  issue_type?: string
  parent?: string
  created_at?: string
  closed_at?: string
  dependencies?: TaskDependency[]
  /** IDs of issues that block this issue (from bd blocked command) */
  blocked_by?: string[]
  /** Number of issues blocking this issue (from bd blocked command) */
  blocked_by_count?: number
}

export type TaskCardTask = Task & {
  labels?: string[]
}

export interface TokenUsage {
  input: number
  output: number
}

export interface ContextWindow {
  used: number
  max: number
}

export interface SessionInfo {
  current: number
  total: number
}

export interface EventLogMetadata {
  taskId?: string
  title?: string
  source?: string
  workspacePath?: string
}

export interface EventLog {
  id: string
  createdAt: string
  events: ChatEvent[]
  metadata?: EventLogMetadata
}

export interface TaskChatMessage {
  id: string
  role: "user" | "assistant"
  content: string
  timestamp: number
  /** Sequence number for ordering within a turn (lower = earlier) */
  sequence?: number
}

export interface TaskChatToolUse {
  toolUseId: string
  tool: string
  input: Record<string, unknown>
  output?: string
  error?: string
  status: "pending" | "running" | "success" | "error"
  /** Timestamp when this tool use was created on the server */
  timestamp: number
  /** Sequence number for ordering within a turn (lower = earlier) */
  sequence?: number
}

export type TaskUpdateData = {
  title?: string
  description?: string
  status?: TaskStatus
  priority?: number
  type?: string
  parent?: string | null
}

/** @deprecated Use `AssistantTextChatEvent` instead. */
export type AssistantTextEvent = AssistantTextChatEvent

/** @deprecated Use `UserMessageChatEvent` instead. */
export type UserMessageEvent = UserMessageChatEvent

/** @deprecated Use `TaskLifecycleChatEvent` instead. */
export type TaskLifecycleEventData = TaskLifecycleChatEvent

/** @deprecated Use `ErrorChatEvent` instead. */
export type ErrorEventData = ErrorChatEvent

export type ToolName =
  | "Read"
  | "Edit"
  | "Write"
  | "Bash"
  | "Grep"
  | "Glob"
  | "WebSearch"
  | "WebFetch"
  | "TodoWrite"
  | "Task"

/** @deprecated Use `ToolUseChatEvent` instead. */
export type ToolUseEvent = ToolUseChatEvent

export interface AssistantTextContentBlock {
  type: "text"
  text: string
}

export interface AssistantThinkingContentBlock {
  type: "thinking"
  thinking: string
}

export interface AssistantToolUseContentBlock {
  type: "tool_use"
  id: string
  name: string
  input: Record<string, unknown>
}

export type AssistantContentBlock =
  | AssistantTextContentBlock
  | AssistantThinkingContentBlock
  | AssistantToolUseContentBlock

export interface StreamingTextBlock {
  type: "text"
  text: string
}

export interface StreamingThinkingBlock {
  type: "thinking"
  thinking: string
}

export interface StreamingToolUseBlock {
  type: "tool_use"
  id: string
  name: string
  input: string
}

export type StreamingContentBlock =
  | StreamingTextBlock
  | StreamingThinkingBlock
  | StreamingToolUseBlock

export interface StreamingMessage {
  timestamp: number
  contentBlocks: StreamingContentBlock[]
}

export type TaskGroup = "open" | "deferred" | "closed"

export interface RelatedTask {
  id: string
  title: string
  status: TaskStatus
  dependency_type?: string
}

export interface ThemeGroup {
  type: "dark" | "light"
  themes: ThemeMeta[]
}

export interface HotkeyCategory {
  name: string
  hotkeys: Array<{ action: HotkeyAction; config: HotkeyConfig }>
}

export interface DiffLine {
  type: "context" | "added" | "removed"
  lineOld?: number
  lineNew?: number
  content: string
}

export interface Comment {
  id: number
  issue_id: string
  author: string
  text: string
  created_at: string
}

export interface WorkspaceInfo {
  path: string
  name: string
  issueCount?: number
  daemonConnected?: boolean
  daemonStatus?: string
  accentColor?: string | null
  branch?: string | null
  issuePrefix?: string | null
}

export interface WorkspaceListEntry {
  path: string
  name: string
  database: string
  pid: number
  version: string
  startedAt: string
  isActive: boolean
  accentColor?: string | null
  activeIssueCount?: number
}

/**  Information about a merge conflict for an instance. */
export interface MergeConflict {
  /** Files with conflicts that need resolution */
  files: string[]
  /** Branch being merged from */
  sourceBranch: string
  /** Timestamp when the conflict was detected */
  timestamp: number
}

/**
 * Represents a single Ralph instance with its per-instance state.
 * Used for concurrent Ralph support where multiple instances can run simultaneously.
 */
export interface RalphInstance {
  /** Unique identifier for the instance */
  id: string

  /** Display name for the instance (e.g., "Main", "Worktree 1") */
  name: string

  /** Agent name/ID used for task assignment (e.g., "Ralph-1", "Ralph-2") */
  agentName: string

  /** Ralph process status */
  status: RalphStatus

  /** Event stream from Ralph for this instance */
  events: ChatEvent[]

  /** Token usage for this instance */
  tokenUsage: TokenUsage

  /** Context window usage for this instance */
  contextWindow: ContextWindow

  /** Session progress for this instance */
  session: SessionInfo

  /** Path to the git worktree (null for main workspace) */
  worktreePath: string | null

  /** Git branch name for this instance */
  branch: string | null

  /** ID of the current task being worked on */
  currentTaskId: string | null

  /** Timestamp when the instance was created */
  createdAt: number

  /** Timestamp when Ralph started running (null if not running) */
  runStartedAt: number | null

  /** Merge conflict info if instance is paused due to merge conflicts (null if no conflict) */
  mergeConflict: MergeConflict | null
}

/**
 * Serialized instance metadata from the server.
 * Contains only persistent/identity fields, not runtime state like events.
 */
export interface SerializedInstance {
  id: string
  name: string
  agentName: string
  worktreePath: string | null
  branch: string | null
  createdAt: number
  currentTaskId: string | null
  status: RalphStatus
  mergeConflict: MergeConflict | null
}
