/** Base chat event interface. */
export interface ChatEvent {
  type: string
  timestamp?: number
  /** Unique identifier for deduplication. Generated by server if not present. */
  id?: string
  [key: string]: unknown
}

/** A user message sent as plain text. */
export interface UserMessageChatEvent extends ChatEvent {
  type: "user_message"
  message: string
}

/** A user turn, which may include tool results. */
export interface UserChatEvent extends ChatEvent {
  type: "user"
  message?: {
    role: string
    content: Array<{
      type: string
      tool_use_id?: string
      content?: string
      is_error?: boolean
      [key: string]: unknown
    }>
  }
  tool_use_result?: unknown
}

/** An assistant response with structured content blocks. */
export interface AssistantChatEvent extends ChatEvent {
  type: "assistant"
  message?: {
    id?: string
    content: AssistantContentBlock[]
    [key: string]: unknown
  }
}

/** A raw streaming event from the Claude SDK. */
export interface StreamChatEvent extends ChatEvent {
  type: "stream_event"
  event?: StreamEventPayload
}

/** Payload of a streaming event from the Claude SDK. */
export interface StreamEventPayload {
  type?: string
  message?: { id?: string; [key: string]: unknown }
  content_block?: {
    type?: string
    text?: string
    thinking?: string
    id?: string
    name?: string
    [key: string]: unknown
  }
  delta?: {
    type?: string
    text?: string
    thinking?: string
    partial_json?: string
    [key: string]: unknown
  }
  [key: string]: unknown
}

/** A result event with token usage information. */
export interface ResultChatEvent extends ChatEvent {
  type: "result"
  usage?: {
    inputTokens?: number
    outputTokens?: number
    totalTokens?: number
    input_tokens?: number
    output_tokens?: number
  }
}

/** An error event. */
export interface ErrorChatEvent extends ChatEvent {
  type: "error" | "server_error"
  error: string
}

/** A tool use event with execution metadata. */
export interface ToolUseChatEvent extends ChatEvent {
  type: "tool_use"
  tool: ToolName
  input?: Record<string, unknown>
  output?: string
  status?: "pending" | "running" | "success" | "error"
  duration?: number
  error?: string
}

/** Emitted when Ralph starts working on a task. */
export interface RalphTaskStartedChatEvent extends ChatEvent {
  type: "ralph_task_started"
  taskId?: string
  sessionId?: string
}

/** Emitted when Ralph finishes working on a task. */
export interface RalphTaskCompletedChatEvent extends ChatEvent {
  type: "ralph_task_completed"
  taskId?: string
  sessionId?: string
}

/** Emitted at the start of a Ralph session. */
export interface RalphSessionStartChatEvent extends ChatEvent {
  type: "ralph_session_start"
  sessionId?: string
}

/** Emitted at the end of a Ralph session. */
export interface RalphSessionEndChatEvent extends ChatEvent {
  type: "ralph_session_end"
  sessionId?: string
}

/** A system event (e.g., init). */
export interface SystemChatEvent extends ChatEvent {
  type: "system"
  subtype?: string
}

/** An assistant text event (plain text content). */
export interface AssistantTextChatEvent extends ChatEvent {
  type: "assistant_text" | "text"
  content: string
}

/** A task lifecycle event. */
export interface TaskLifecycleChatEvent extends ChatEvent {
  type: "task_lifecycle"
  action: "starting" | "completed"
  taskId: string
}

/** A promise complete event, emitted when a session signals completion. */
export interface PromiseCompleteChatEvent extends ChatEvent {
  type: "promise_complete"
}

/** @deprecated Use `AssistantTextChatEvent` instead. */
export type AssistantTextEvent = AssistantTextChatEvent

/** @deprecated Use `UserMessageChatEvent` instead. */
export type UserMessageEvent = UserMessageChatEvent

/** @deprecated Use `TaskLifecycleChatEvent` instead. */
export type TaskLifecycleEventData = TaskLifecycleChatEvent

/** @deprecated Use `ErrorChatEvent` instead. */
export type ErrorEventData = ErrorChatEvent

export type ToolName =
  | "Read"
  | "Edit"
  | "Write"
  | "Bash"
  | "Grep"
  | "Glob"
  | "WebSearch"
  | "WebFetch"
  | "TodoWrite"
  | "Task"

/** @deprecated Use `ToolUseChatEvent` instead. */
export type ToolUseEvent = ToolUseChatEvent

export interface AssistantTextContentBlock {
  type: "text"
  text: string
}

export interface AssistantThinkingContentBlock {
  type: "thinking"
  thinking: string
}

export interface AssistantToolUseContentBlock {
  type: "tool_use"
  id: string
  name: string
  input: Record<string, unknown>
}

export type AssistantContentBlock =
  | AssistantTextContentBlock
  | AssistantThinkingContentBlock
  | AssistantToolUseContentBlock

export interface StreamingTextBlock {
  type: "text"
  text: string
}

export interface StreamingThinkingBlock {
  type: "thinking"
  thinking: string
}

export interface StreamingToolUseBlock {
  type: "tool_use"
  id: string
  name: string
  input: string
}

export type StreamingContentBlock =
  | StreamingTextBlock
  | StreamingThinkingBlock
  | StreamingToolUseBlock

export interface StreamingMessage {
  timestamp?: number
  contentBlocks: StreamingContentBlock[]
}

/** Token usage summary for input/output tokens. */
export interface TokenUsage {
  input: number
  output: number
}

/** Context window usage data. */
export interface ContextWindow {
  used: number
  max: number
}

/** A single parsed diff line. */
export interface DiffLine {
  type: "context" | "added" | "removed"
  lineOld?: number
  lineNew?: number
  content: string
}

/** Link handling options for text rendering. */
export interface AgentViewLinkHandlers {
  taskIdPrefix?: string | null
  buildTaskHref?: (taskId: string) => string
  buildSessionHref?: (sessionId: string) => string
  onTaskClick?: (taskId: string) => void
  onSessionClick?: (sessionId: string) => void
}

/** Tool output visibility controls. */
export interface AgentViewToolOutputControl {
  isVisible: boolean
  onToggle: () => void
}

/** A task entry for display purposes. */
export interface AgentViewTask {
  id: string
  title?: string
}

/** Context values shared by agent-view components. */
export interface AgentViewContextValue {
  isDark: boolean
  linkHandlers: AgentViewLinkHandlers
  toolOutput?: AgentViewToolOutputControl
  workspacePath?: string | null
  /** Available tasks for task ID lookups (e.g., in TaskLifecycleEvent). */
  tasks?: AgentViewTask[]
}
