export { MainLayout, type MainLayoutProps, type MainLayoutHandle } from "./MainLayout"
export { Header, type HeaderProps } from "./Header"
export { StatusBar, type StatusBarProps } from "./StatusBar"
export { WorkspacePicker, type WorkspacePickerProps } from "./WorkspacePicker"
export type { WorkspaceInfo } from "@/types"
export { HotkeysDialog, type HotkeysDialogProps } from "./HotkeysDialog"
export { HelpButton, type HelpButtonProps } from "./HelpButton"
export { CommandPalette, type CommandPaletteProps, type CommandAction } from "./CommandPalette"
export { InstanceCountBadge, type InstanceCountBadgeProps } from "./InstanceCountBadge"
export { InstanceSelector, type InstanceSelectorProps } from "./InstanceSelector"
export { NewInstanceDialog, type NewInstanceDialogProps } from "./NewInstanceDialog"
export { SettingsDropdown, type SettingsDropdownProps } from "./SettingsDropdown"
